import 'package:flutter/material.dart';
import '../services/world_time.dart';

class ChooseLocation extends StatefulWidget {
  const ChooseLocation({super.key});

  @override
  State<ChooseLocation> createState() => _ChooseLocationState();
}

class _ChooseLocationState extends State<ChooseLocation> {

  List<WorldTime> filteredLocations = [];
  bool isSearching = false;
  final TextEditingController _searchController = TextEditingController();

  List<WorldTime> locations = [
    WorldTime(url: 'Africa/Abidjan', location: 'Abidjã', country: 'Costa do Marfim', flag: 'costa_do_marfim.png', isDaytime: true),
    // ... many more entries
    WorldTime(url: 'Africa/Accra', location: 'Acra', country: 'Gana', flag: 'gana.png', isDaytime: true),
    WorldTime(url: 'Africa/Addis_Ababa', location: 'Adis Ababa', country: 'Etiópia', flag: 'ethiopia.png', isDaytime: true),
    WorldTime(url: 'Africa/Algiers', location: 'Argel', country: 'Argélia', flag: 'algeria.png', isDaytime: true),
    WorldTime(url: 'Africa/Asmara', location: 'Asmara', country: 'Eritréia', flag: 'eritreia.png', isDaytime: true),
    WorldTime(url: 'Africa/Asmera', location: 'Asmera', country: 'Eritréia', flag: 'eritreia.png', isDaytime: true),
    WorldTime(url: 'Africa/Bamako', location: 'Bamaco', country: 'Mali', flag: 'mali.png', isDaytime: true),
    WorldTime(url: 'Africa/Bangui', location: 'Bangui', country: 'República Centro Africana', flag: 'central_republic_african.png', isDaytime: true),
    WorldTime(url: 'Africa/Banjul', location: 'Banjul', country: 'Gâmbia', flag: 'gambia.png', isDaytime: true),
    WorldTime(url: 'Africa/Bissau', location: 'Bissau', country: 'Guiné Bissau', flag: 'guinea_bissau.png', isDaytime: true),
    WorldTime(url: 'Africa/Blantyre', location: 'Blantire', country: 'Malawi', flag: 'malawi.png', isDaytime: true),
    WorldTime(url: 'Africa/Brazzaville', location: 'Brazavile', country: 'Congo', flag: 'congo.png', isDaytime: true),
    WorldTime(url: 'Africa/Bujumbura', location: 'Bujumbura', country: 'Burundi', flag: 'burundi.png', isDaytime: true),
    WorldTime(url: 'Africa/Cairo', location: 'Cairo', country: 'Egito', flag: 'egito.png', isDaytime: true),
    WorldTime(url: 'Africa/Casablanca', location: 'Casablanca', country: 'Marrocos', flag: 'marrocos.png', isDaytime: true),
    WorldTime(url: 'Africa/Ceuta', location: 'Ceuta', country: 'Espanha', flag: 'ceuta.png', isDaytime: true),
    WorldTime(url: 'Africa/Conakry', location: 'Conacri', country: 'Guiné', flag: 'guinea.png', isDaytime: true),
    WorldTime(url: 'Africa/Dakar', location: 'Dacar', country: 'Senegal', flag: 'senegal.png', isDaytime: true),
    WorldTime(url: 'Africa/Dar_es_Salaam', location: 'Dar es Salaam', country: 'Tanzânia', flag: 'tanzania.png', isDaytime: true),
    WorldTime(url: 'Africa/Djibouti', location: 'Djibuti', country: 'Djibuti', flag: 'djibouti.png', isDaytime: true),
    WorldTime(url: 'Africa/Douala', location: 'Duala', country: 'Camarões', flag: 'cameroon.png', isDaytime: true),
    WorldTime(url: 'Africa/El_Aaiun', location: 'El Aiune', country: 'Saara Ocidental', flag: 'saara_ocidental.png', isDaytime: true),
    WorldTime(url: 'Africa/Freetown', location: 'Freetown', country: 'Serra Leoa', flag: 'serra_leoa.png', isDaytime: true),
    WorldTime(url: 'Africa/Gaborone', location: 'Gaborone', country: 'Botswana', flag: 'botswana.png', isDaytime: true),
    WorldTime(url: 'Africa/Harare', location: 'Harare', country: 'Zimbábue', flag: 'zimbabwe.png', isDaytime: true),
    WorldTime(url: 'Africa/Johannesburg', location: 'Joanesburgo', country: 'África do Sul', flag: 'south_africa.png', isDaytime: true),
    WorldTime(url: 'Africa/Juba', location: 'Juba', country: 'Sudão do Sul', flag: 'south_sudan.png', isDaytime: true),
    WorldTime(url: 'Africa/Kampala', location: 'Campala', country: 'Uganda', flag: 'uganda.png', isDaytime: true),
    WorldTime(url: 'Africa/Khartoum', location: 'Cartum', country: 'Sudão', flag: 'sudan.png', isDaytime: true),
    WorldTime(url: 'Africa/Kigali', location: 'Quigali', country: 'Ruanda', flag: 'ruanda.png', isDaytime: true),
    WorldTime(url: 'Africa/Kinshasa', location: 'Quinxassa', country: 'República Democrática do Congo', flag: 'democratic_republic_of_the_congo.png', isDaytime: true),
    WorldTime(url: 'Africa/Lagos', location: 'Lagos', country: 'Nigéria', flag: 'nigeria.png', isDaytime: true),
    WorldTime(url: 'Africa/Libreville', location: 'Libreville', country: 'Gabão', flag: 'gabon.png', isDaytime: true),
    WorldTime(url: 'Africa/Lome', location: 'Lomé', country: 'Togo', flag: 'togo.png', isDaytime: true),
    WorldTime(url: 'Africa/Luanda', location: 'Luanda', country: 'Angola', flag: 'angola.png', isDaytime: true),
    WorldTime(url: 'Africa/Lubumbashi', location: 'Lubumbashi', country: 'República Democrática do Congo', flag: 'democratic_republic_of_the_congo.png', isDaytime: true),
    WorldTime(url: 'Africa/Lusaka', location: 'Lusaca', country: 'Zâmbia', flag: 'zambia.png', isDaytime: true),
    WorldTime(url: 'Africa/Malabo', location: 'Malabo', country: 'Guiné Equatorial', flag: 'equatorial_guinea.png', isDaytime: true),
    WorldTime(url: 'Africa/Maputo', location: 'Maputo', country: 'Moçambique', flag: 'mozambique.png', isDaytime: true),
    WorldTime(url: 'Africa/Maseru', location: 'Maseru', country: 'Lesoto', flag: 'lesoto.png', isDaytime: true),
    WorldTime(url: 'Africa/Mbabane', location: 'Mebabane', country: 'Essuatíni', flag: 'eswatini.png', isDaytime: true),
    WorldTime(url: 'Africa/Mogadishu', location: 'Mogadíscio', country: 'Somália', flag: 'somalia.png', isDaytime: true),
    WorldTime(url: 'Africa/Monrovia', location: 'Monróvia', country: 'Libéria', flag: 'liberia.png', isDaytime: true),
    WorldTime(url: 'Africa/Nairobi', location: 'Nairóbi', country: 'Quênia', flag: 'kenya.png', isDaytime: true),
    WorldTime(url: 'Africa/Ndjamena', location: 'Jamena', country: 'Chade', flag: 'chade.png', isDaytime: true),
    WorldTime(url: 'Africa/Niamey', location: 'Niamei', country: 'Níger', flag: 'niger.png', isDaytime: true),
    WorldTime(url: 'Africa/Nouakchott', location: 'Nouakchott', country: 'Mauritânia', flag: 'mauritania.png', isDaytime: true),
    WorldTime(url: 'Africa/Ouagadougou', location: 'Uagadugu', country: 'Burkina Faso', flag: 'burkina_faso.png', isDaytime: true),
    WorldTime(url: 'Africa/Porto-Novo', location: 'Porto Novo', country: 'Benin', flag: 'benin.png', isDaytime: true),
    WorldTime(url: 'Africa/Sao_Tome', location: 'São Tomé', country: 'São Tomé e Príncipe', flag: 'sao_tome_e_principe.png', isDaytime: true),
    WorldTime(url: 'Africa/Timbuktu', location: 'Tombuctu', country: 'Mali', flag: 'mali.png', isDaytime: true),
    WorldTime(url: 'Africa/Tripoli', location: 'Trípoli', country: 'Líbia', flag: 'libya.png', isDaytime: true),
    WorldTime(url: 'Africa/Tunis', location: 'Tunes', country: 'Tunísia', flag: 'tunisia.png', isDaytime: true),
    WorldTime(url: 'Africa/Windhoek', location: 'Vinduque', country: 'Namíbia', flag: 'namibia.png', isDaytime: true),
    WorldTime(url: 'America/Adak', location: 'Adak', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Anchorage', location: 'Anchorague', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Anguilla', location: 'Anguila', country: 'Reino Unido', flag: 'anguila.png', isDaytime: true),
    WorldTime(url: 'America/Antigua', location: 'Antígua', country: 'Antígua e Barbuda', flag: 'antigua_and_barbuda.png', isDaytime: true),
    WorldTime(url: 'America/Araguaina', location: 'Araguaína', country: 'Brasil', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Argentina/Buenos_Aires', location: 'Buenos Aires', country: 'Argentina', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Argentina/Catamarca', location: 'Catamarca', country: 'Argentina', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Argentina/ComodRivadavia', location: 'Comodoro Rivadaria', country: 'Argentina', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Argentina/Cordoba', location: 'Córdova', country: 'Argentina', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Argentina/Jujuy', location: 'Jujuy', country: 'Argentina', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Argentina/La_Rioja', location: 'La Rioja', country: 'Argentina', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Argentina/Mendoza', location: 'Mendoza', country: 'Argentina', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Argentina/Rio_Gallegos', location: 'Río Gallegos', country: 'Argentina', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Argentina/Salta', location: 'Salta', country: 'Argentina', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Argentina/San_Juan', location: 'San Juan', country: 'Argentina', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Argentina/San_Luis', location: 'San Luis', country: 'Argentina', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Argentina/Tucuman', location: 'Tucumã', country: 'Argentina', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Argentina/Ushuaia', location: 'Ushuaia', country: 'Argentina', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Aruba', location: 'Aruba', country: 'Países Baixos', flag: 'aruba.png', isDaytime: true),
    WorldTime(url: 'America/Asuncion', location: 'Assunção', country: 'Paraguai', flag: 'paraguai.png', isDaytime: true),
    WorldTime(url: 'America/Atikokan', location: 'Atikokan', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Atka', location: 'Atka', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Bahia', location: 'Bahia', country: 'Brasil', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Bahia_Banderas', country: 'México', location: 'Bahía de Banderas', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'America/Barbados', location: 'Barbados', country: 'Barbados', flag: 'barbados.png', isDaytime: true),
    WorldTime(url: 'America/Belem', location: 'Belém', country: 'Brasil', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Belize', location: 'Belize', country: 'Belize', flag: 'belize.png', isDaytime: true),
    WorldTime(url: 'America/Blanc_Sablon', location: 'Blanc-Sablon', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Boa_Vista', location: 'Boa Vista', country: 'Brasil', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Bogota', location: 'Bogotá', country: 'Colômbia', flag: 'colombia.png', isDaytime: true),
    WorldTime(url: 'America/Boise', location: 'Boise', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Buenos_Aires', location: 'Buenos Aires', country: 'Argentina', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Cambridge_Bay', location: 'Cambridge Bay', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Campo_Grande', location: 'Campo Grande', country: 'Brasil', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Cancun', location: 'Cancún', country: 'México', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'America/Caracas', location: 'Caracas', country: 'Venezuela', flag: 'venezuela.png', isDaytime: true),
    WorldTime(url: 'America/Catamarca', location: 'Catamarca', country: 'Argentina', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Cayenne', location: 'Cayenne', country: 'França', flag: 'guiana_francesa.png', isDaytime: true),
    WorldTime(url: 'America/Cayman', location: 'Cayman', country: 'Reino Unido', flag: 'ilhas_cayman.png', isDaytime: true),
    WorldTime(url: 'America/Chicago', location: 'Chicago', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Chihuahua', location: 'Chihuahua', country: 'México', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'America/Ciudad_Juarez', location: 'Ciudad Juárez', country: 'México', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'America/Coral_Harbour', location: 'Coral Harbour', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Cordoba', location: 'Córdova', country: 'Argentina', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Costa_Rica', location: 'Costa Rica', country: 'Costa Rica', flag: 'costa_rica.png', isDaytime: true),
    WorldTime(url: 'America/Creston', location: 'Creston', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Cuiaba', location: 'Cuiabá', country: 'Brasil', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Curacao', location: 'Curaçao', country: 'Curaçao', flag: 'curacao.png', isDaytime: true),
    WorldTime(url: 'America/Danmarkshavn', location: 'Danmarkshavn', country: 'Dinamarca', flag: 'greenland.png', isDaytime: true),
    WorldTime(url: 'America/Dawson', location: 'Dawson', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Dawson_Creek', location: 'Dawson Creek', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Denver', location: 'Denver', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Detroit', location: 'Detroit', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Dominica', location: 'Dominica', country: 'Dominica', flag: 'dominica.png', isDaytime: true),
    WorldTime(url: 'America/Edmonton', location: 'Edmonton', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Eirunepe', location: 'Eirunepé', country: 'Brasil', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/El_Salvador', location: 'El Salvador', country: 'El Salvador', flag: 'el_salvador.png', isDaytime: true),
    WorldTime(url: 'America/Ensenada', location: 'Ensenada', country: 'México', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'America/Fort_Nelson', location: 'Fort Nelson', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Fort_Wayne', location: 'Fort Wayne', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Fortaleza', location: 'Fortaleza', country: 'Brasil', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Glace_Bay', location: 'Glace Bay', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Godthab', location: 'Godthab', country: 'Dinamarca', flag: 'greenland.png', isDaytime: true),
    WorldTime(url: 'America/Goose_Bay', location: 'Goose Bay', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Grand_Turk', location: 'Grande Turca', country: 'Reino Unido', flag: 'ilhas_turcas_e_caicos.png', isDaytime: true),
    WorldTime(url: 'America/Grenada', location: 'Granada', country: 'Granada', flag: 'granada.png', isDaytime: true),
    WorldTime(url: 'America/Guadeloupe', location: 'Guadalupe', country: 'França', flag: 'guadalupe.png', isDaytime: true),
    WorldTime(url: 'America/Guatemala', location: 'Guatemala', country: 'Guatemala', flag: 'guatemala.png', isDaytime: true),
    WorldTime(url: 'America/Guayaquil', location: 'Guaiaquil', country: 'Equador', flag: 'equador.png', isDaytime: true),
    WorldTime(url: 'America/Guyana', location: 'Guiana', country: 'Guiana', flag: 'guiana.png', isDaytime: true),
    WorldTime(url: 'America/Halifax', location: 'Halifax', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Havana', location: 'Havana', country: 'Cuba', flag: 'cuba.png', isDaytime: true),
    WorldTime(url: 'America/Hermosillo', location: 'Hermosillo', country: 'México', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'America/Indiana/Indianapolis', location: 'Indianápolis', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Indiana/Knox', location: 'Knox', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Indiana/Marengo', location: 'Marengo', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Indiana/Petersburg', location:  'Petersburg', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Indiana/Tell_City', location: 'Tell City', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Indiana/Vevay', location: 'Vevay', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Indiana/Vincennes', location: 'Vincennes', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Indiana/Winamac', location: 'Winamac', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Indianapolis', location: 'Indianápolis', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Inuvik', location: 'Inuvik', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Iqaluit', location: 'Iqaluit', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Jamaica', location: 'Jamaica', country: 'Jamaica', flag: 'jamaica.png', isDaytime: true),
    WorldTime(url: 'America/Jujuy', location: 'Jujuy', country: 'Argentina', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Juneau', location: 'Juneau', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Kentucky/Louisville', location: 'Louisville', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Kentucky/Monticello', location: 'Monticello', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Knox_IN', location: 'Knox', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Kralendijk', location: 'Kralendijk', country: 'Países Baixos', flag: 'nederland.png', isDaytime: true),
    WorldTime(url: 'America/La_Paz', location: 'La Paz', country: 'Bolívia', flag: 'bolivia.png', isDaytime: true),
    WorldTime(url: 'America/Lima', location: 'Lima', country: 'Peru', flag: 'peru.png', isDaytime: true),
    WorldTime(url: 'America/Los_Angeles', location: 'Los Angeles', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Louisville', location: 'Louisville', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Lower_Princes', location: 'Lower Princes', country: 'Países Baixos', flag: 'nederland.png', isDaytime: true),
    WorldTime(url: 'America/Maceio', location: 'Maceió', country: 'Brasil', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Managua', location: 'Manágua', country: 'Nicarágua', flag: 'nicaragua.png', isDaytime: true),
    WorldTime(url: 'America/Manaus', location: 'Manaus', country: 'Brasil', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Marigot', location: 'Marigot', country: 'França', flag: 'france.png', isDaytime: true),
    WorldTime(url: 'America/Martinique', location: 'Martinica', country: 'França', flag: 'martinica.png', isDaytime: true),
    WorldTime(url: 'America/Matamoros', location: 'Matamoros', country: 'México', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'America/Mazatlan', location: 'Mazatlán', country: 'México', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'America/Mendoza', location: 'Mendoza', country: 'Argentina', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Menominee', location: 'Menominee', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Merida', location: 'Mérida', country: 'México', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'America/Metlakatla', location: 'Metlakatla', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Mexico_City', location: 'Cidade do México', country: 'México', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'America/Miquelon', location: 'Miquelão', country: 'França', flag: 'france.png', isDaytime: true),
    WorldTime(url: 'America/Moncton', location: 'Moncton', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Monterrey', location: 'Monterrey', country: 'México', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'America/Montevideo', location: 'Montevidéu', country: 'Uruguai', flag: 'uruguai.png', isDaytime: true),
    WorldTime(url: 'America/Montreal', location: 'Montreal', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Montserrat', location: 'Monserrate', country: 'Reino Unido', flag: 'monserrate.png', isDaytime: true),
    WorldTime(url: 'America/Nassau', location: 'Nassau', country: 'Bahamas', flag: 'bahamas.png', isDaytime: true),
    WorldTime(url: 'America/New_York', location: 'Nova Iorque', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Nipigon', location: 'Nipigon', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Nome', location: 'Nome', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Noronha', location: 'Fernando de Noronha', country: 'Brasil', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/North_Dakota/Beulah', location: 'Beulah', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/North_Dakota/Center', location: 'Center', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/North_Dakota/New_Salem', location: 'New Salem', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Nuuk', location: 'Nuuk', country: 'Dinamarca', flag: 'greenland.png', isDaytime: true),
    WorldTime(url: 'America/Ojinaga', location: 'Ojinaga', country: 'México', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'America/Panama', location: 'Panamá', country: 'Panamá', flag: 'panama.png', isDaytime: true),
    WorldTime(url: 'America/Pangnirtung', location: 'Pangnirtung', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Paramaribo', location: 'Paramaribo', country: 'Suriname', flag: 'suriname.png', isDaytime: true),
    WorldTime(url: 'America/Phoenix', location: 'Phoenix', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Port-au-Prince', location: 'Port-au-Prince', country: 'Haiti', flag: 'haiti.png', isDaytime: true),
    WorldTime(url: 'America/Port_of_Spain', location: 'Porto da Espanha', country: 'Trindade e Tobago', flag: 'trindade_e_tobago.png', isDaytime: true),
    WorldTime(url: 'America/Porto_Acre', location: 'Porto Acre', country: 'Brasil', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Porto_Velho', location: 'Porto Velho', country: 'Brasil', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Puerto_Rico', location: 'Porto Rico', country: 'Porto Rico', flag: 'porto_rico.png', isDaytime: true),
    WorldTime(url: 'America/Punta_Arenas', location: 'Punta Arenas', country: 'Chile', flag: 'chile.png', isDaytime: true),
    WorldTime(url: 'America/Rainy_River', location: 'Rainy River', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Rankin_Inlet', location: 'Rankin Inlet', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Recife', location: 'Recife', country: 'Brasil', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Regina', location: 'Regina', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Resolute', location: 'Resolute', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Rio_Branco', location: 'Rio Branco', country: 'Brasil', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Rosario', location: 'Rosário', country: 'Argentina', flag: 'argentina.png', isDaytime: true),
    WorldTime(url: 'America/Santa_Isabel', location: 'Santa Isabel', country: 'Brasil', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Santarem', location: 'Santarém', country: 'Brasil', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Santiago', location: 'Santiago', country: 'Chile', flag: 'chile.png', isDaytime: true),
    WorldTime(url: 'America/Santo_Domingo', location: 'Santo Domingo', country: 'República Dominicana', flag: 'dominican_republic.png', isDaytime: true),
    WorldTime(url: 'America/Sao_Paulo', location: 'São Paulo', country: 'Brasil', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'America/Scoresbysund', location: 'Ittoqqortoormiit', country: 'Dinamarca', flag: 'greenland.png', isDaytime: true),
    WorldTime(url: 'America/Shiprock', location: 'Shiprock', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Sitka', location: 'Sitka', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/St_Barthelemy', location: 'São Bartolomeu', country: 'França', flag: 'france.png', isDaytime: true),
    WorldTime(url: 'America/St_Johns', location: 'St. John', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/St_Kitts', location: 'São Cristóvão e Neves', country: 'São Cristóvão e Neves', flag: 'saint_kitts_and_nevis.png', isDaytime: true),
    WorldTime(url: 'America/St_Lucia', location: 'Santa Lúcia', country: 'Santa Lúcia', flag: 'saint_lucia.png', isDaytime: true),
    WorldTime(url: 'America/St_Thomas', location: 'St. Thomas', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/St_Vincent', location: 'São Vicente e Granadinas', country: 'São Vicente e Granadinas', flag: 'saint_vicent_and_the_grenadines.png', isDaytime: true),
    WorldTime(url: 'America/Swift_Current', location: 'Swift Current', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Tegucigalpa', location: 'Tegucigalpa', country: 'Honduras', flag: 'honduras.png', isDaytime: true),
    WorldTime(url: 'America/Thule', location: 'Thule', country: 'Reino Unido', flag: 'reino_unido.png', isDaytime: true),
    WorldTime(url: 'America/Thunder_Bay', location: 'Thunder Bay', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Tijuana', location: 'Tijuana', country: 'México', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'America/Toronto', location: 'Toronto', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Tortola', location: 'Tortola', country: 'Reino Unido', flag: 'reino_unido.png', isDaytime: true),
    WorldTime(url: 'America/Vancouver', location: 'Vancouver', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Virgin', location: 'Virgínia', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Whitehorse', location: 'Whitehorse', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Winnipeg', location: 'Winnipeg', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'America/Yakutat', location: 'Yakutat', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'America/Yellowknife', location: 'Yellowknife', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'Antarctica/Casey', location: 'Casey', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Antarctica/Davis', location: 'Davis', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Antarctica/DumontDUrville', location: 'DumontDUrville', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Antarctica/Macquarie', location: 'Macquarie', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Antarctica/Mawson', location: 'Mawson', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Antarctica/McMurdo', location: 'McMurdo', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Antarctica/Palmer', location: 'Palmer', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Antarctica/Rothera', location: 'Rothera', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Antarctica/South_Pole', location: 'Polo Sul', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Antarctica/Syowa', location: 'Syowa', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Antarctica/Troll', location: 'Troll', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Antarctica/Vostok', location: 'Vostok', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Arctic/Longyearbyen', location: 'Longyearbyen', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Asia/Aden', location: 'Adem', country: 'Iêmen', flag: 'yemen.png', isDaytime: true),
    WorldTime(url: 'Asia/Almaty', location: 'Almati', country: 'Cazaquistão', flag: 'kazakhstan.png', isDaytime: true),
    WorldTime(url: 'Asia/Amman', location: 'Amã', country: 'Jordânia', flag: 'jordan.png', isDaytime: true),
    WorldTime(url: 'Asia/Anadyr', location: 'Anadyr', country: 'Rússia', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Aqtau', location: 'Aqtau', country: 'Cazaquistão', flag: 'kazakhstan.png', isDaytime: true),
    WorldTime(url: 'Asia/Aqtobe', location: 'Aqtöbe', country: 'Cazaquistão', flag: 'kazakhstan.png', isDaytime: true),
    WorldTime(url: 'Asia/Ashgabat', location: 'Ashgabat', country: 'Turcomenistão', flag: 'turkmenistan.png', isDaytime: true),
    WorldTime(url: 'Asia/Ashkhabad', location: 'Asgabade', country: 'Turcomenistão', flag: 'turkmenistan.png', isDaytime: true),
    WorldTime(url: 'Asia/Atyrau', location: 'Atyrau', country: 'Cazaquistão', flag: 'kazakhstan.png', isDaytime: true),
    WorldTime(url: 'Asia/Baghdad', location: 'Bagdá', country: 'Iraque', flag: 'iraque.png', isDaytime: true),
    WorldTime(url: 'Asia/Bahrain', location: 'Bahrein', country: 'Bahrein', flag: 'bahrein.png', isDaytime: true),
    WorldTime(url: 'Asia/Baku', location: 'Bacu', country: 'Azerbaijão', flag: 'azerbaijan.png', isDaytime: true),
    WorldTime(url: 'Asia/Bangkok', location: 'Banguecoque', country: 'Tailândia', flag: 'thailand.png', isDaytime: true),
    WorldTime(url: 'Asia/Barnaul', location: 'Barnaul', country: 'Rússia', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Beirut', location: 'Beirute', country: 'Líbano', flag: 'lebanon.png', isDaytime: true),
    WorldTime(url: 'Asia/Bishkek', location: 'Bisqueque', country: 'Quirguistão', flag: 'kyrgyzstan.png', isDaytime: true),
    WorldTime(url: 'Asia/Brunei', location: 'Brunei', country: 'Brunei', flag: 'brunei.png', isDaytime: true),
    WorldTime(url: 'Asia/Calcutta', location: 'Calcutá', country: 'Índia', flag: 'india.png', isDaytime: true),
    WorldTime(url: 'Asia/Chita', location: 'Chitá', country: 'Rússia', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Choibalsan', location: 'Choibalsan', country: 'Mongólia', flag: 'mongolia.png', isDaytime: true),
    WorldTime(url: 'Asia/Chongqing', location: 'Xunquim', country: 'China', flag: 'china.png', isDaytime: true),
    WorldTime(url: 'Asia/Chungking', location: 'Chung Hing Sam Lam', country: 'China', flag: 'china.png', isDaytime: true),
    WorldTime(url: 'Asia/Colombo', location: 'Colombo', country: 'Sri Lanka', flag: 'sri_lanka.png', isDaytime: true),
    WorldTime(url: 'Asia/Dacca', location: 'Dacca', country: 'Bangladesh', flag: 'bangladesh.png', isDaytime: true),
    WorldTime(url: 'Asia/Damascus', location: 'Damasco', country: 'Síria', flag: 'syria.png', isDaytime: true),
    WorldTime(url: 'Asia/Dhaka', location: 'Daca', country: 'Bangladesh', flag: 'bangladesh.png', isDaytime: true),
    WorldTime(url: 'Asia/Dili', location: 'Díli', country: 'Timor Leste', flag: 'timor_leste.png', isDaytime: true),
    WorldTime(url: 'Asia/Dubai', location: 'Dubai', country: 'Emirados Árabes Unidos', flag: 'uae.png', isDaytime: true),
    WorldTime(url: 'Asia/Dushanbe', location: 'Duxambé', country: 'Tadjiquistão', flag: 'tajikistan.png', isDaytime: true),
    WorldTime(url: 'Asia/Famagusta', location: 'Famagusta', country: 'Chipre do Norte', flag: 'chipre_do_norte.png', isDaytime: true),
    WorldTime(url: 'Asia/Gaza', location: 'Gaza', country: 'Palestina', flag: 'palestina.png', isDaytime: true),
    WorldTime(url: 'Asia/Harbin', location: 'Harbin', country: 'China', flag: 'china.png', isDaytime: true),
    WorldTime(url: 'Asia/Hebron', location: 'Hebrom', country: 'Palestina', flag: 'palestina.png', isDaytime: true),
    WorldTime(url: 'Asia/Ho_Chi_Minh', location: 'Ho Chi Minh', country: 'Vietnã', flag: 'vietnam.png', isDaytime: true),
    WorldTime(url: 'Asia/Hong_Kong', location: 'Hong Kong', country: 'Hong Kong', flag: 'hong_kong.png', isDaytime: true),
    WorldTime(url: 'Asia/Hovd', location: 'Khovd', country: 'Mongólia', flag: 'mongolia.png', isDaytime: true),
    WorldTime(url: 'Asia/Irkutsk', location: 'Irkutsk', country: 'Rússia', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Istanbul', location: 'Istambul', country: 'Turquia', flag: 'turquia.png', isDaytime: true),
    WorldTime(url: 'Asia/Jakarta', location: 'Jacarta', country: 'Indonésia', flag: 'indonesia.png', isDaytime: true),
    WorldTime(url: 'Asia/Jayapura', location: 'Jayapura', country: 'Indonésia', flag: 'indonesia.png', isDaytime: true),
    WorldTime(url: 'Asia/Jerusalem', location: 'Jerusalém', country: 'Israel', flag: 'israel.png', isDaytime: true),
    WorldTime(url: 'Asia/Kabul', location: 'Cabul', country: 'Afeganistão', flag: 'afghanistan.png', isDaytime: true),
    WorldTime(url: 'Asia/Kamchatka', location: 'Camecháteca', country: 'Rússia', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Karachi', location: 'Carachi', country: 'Paquistão', flag: 'pakistan.png', isDaytime: true),
    WorldTime(url: 'Asia/Kashgar', location: 'Casgar', country: 'China', flag: 'china.png', isDaytime: true),
    WorldTime(url: 'Asia/Kathmandu', location: 'Catmandu', country: 'Nepal', flag: 'nepal.png', isDaytime: true),
    WorldTime(url: 'Asia/Katmandu', location: 'Katmandu', country: 'Nepal', flag: 'nepal.png', isDaytime: true),
    WorldTime(url: 'Asia/Khandyga', location: 'Khandyga', country: 'Rússia', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Kolkata', location: 'Calcutá', country: 'Índia', flag: 'india.png', isDaytime: true),
    WorldTime(url: 'Asia/Krasnoyarsk', location: 'Krasnoiarsk', country: 'Rússia', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Kuala_Lumpur', location: 'Kuala Lumpur', country: 'Malásia', flag: 'malaysia.png', isDaytime: true),
    WorldTime(url: 'Asia/Kuching', location: 'Kuching', country: 'Malásia', flag: 'malaysia.png', isDaytime: true),
    WorldTime(url: 'Asia/Kuwait', location: 'Kuwait', country: 'Kuwait', flag: 'kuwait.png', isDaytime: true),
    WorldTime(url: 'Asia/Macao', location: 'Macao', country: 'Macau', flag: 'macau.png', isDaytime: true),
    WorldTime(url: 'Asia/Macau', location: 'Macau', country: 'Macau', flag: 'macau.png', isDaytime: true),
    WorldTime(url: 'Asia/Magadan', location: 'Magadan', country: 'Rússia', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Makassar', location: 'Macáçar', country: 'Indonésia', flag: 'indonesia.png', isDaytime: true),
    WorldTime(url: 'Asia/Manila', location: 'Manila', country: 'Filipinas', flag: 'filipinas.png', isDaytime: true),
    WorldTime(url: 'Asia/Muscat', location: 'Mascat', country: 'Omã', flag: 'oman.png', isDaytime: true),
    WorldTime(url: 'Asia/Nicosia', location: 'Nicosia', country: 'Chipre', flag: 'chipre.png', isDaytime: true),
    WorldTime(url: 'Asia/Novokuznetsk', location: 'Novokuznetsk', country: 'Rússia', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Novosibirsk', location: 'Novosibirsk', country: 'Rússia', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Omsk', location: 'Omsk', country: 'Rússia', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Oral', location: 'Oral', country: 'Cazaquistão', flag: 'kazakhstan.png', isDaytime: true),
    WorldTime(url: 'Asia/Phnom_Penh', location: 'Phnom Penh', country: 'Camboja', flag: 'camboja.png', isDaytime: true),
    WorldTime(url: 'Asia/Pontianak', location: 'Pontianak', country: 'Indonésia', flag: 'indonesia.png', isDaytime: true),
    WorldTime(url: 'Asia/Pyongyang', location: 'Pyongyang', country: 'Coreia do Norte', flag: 'coreia_do_norte.png', isDaytime: true),
    WorldTime(url: 'Asia/Qatar', location: 'Catar', country: 'Catar', flag: 'catar.png', isDaytime: true),
    WorldTime(url: 'Asia/Qostanay', location: 'Qostanay', country: 'Cazaquistão', flag: 'kazakhstan.png', isDaytime: true),
    WorldTime(url: 'Asia/Qyzylorda', location: 'Qyzylorda', country: 'Cazaquistão', flag: 'kazakhstan.png', isDaytime: true),
    WorldTime(url: 'Asia/Rangoon', location: 'Rangum', country: 'Myanmar', flag: 'myanmar.png', isDaytime: true),
    WorldTime(url: 'Asia/Riyadh', location: 'Riade', country: 'Arábia Saudita', flag: 'saudi_arabia.png', isDaytime: true),
    WorldTime(url: 'Asia/Saigon', location: 'Saigon', country: 'Vietnã', flag: 'vietnam.png', isDaytime: true),
    WorldTime(url: 'Asia/Sakhalin', location: 'Sacalina', country: 'Rússia', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Samarkand', location: 'Samarcanda', country: 'Uzbequistão', flag: 'uzbekistan.png', isDaytime: true),
    WorldTime(url: 'Asia/Seoul', location: 'Seul', country: 'Coreia do Sul', flag: 'coreia_do_sul.png', isDaytime: true),
    WorldTime(url: 'Asia/Shanghai', location: 'Xangai', country: 'China', flag: 'china.png', isDaytime: true),
    WorldTime(url: 'Asia/Singapore', location: 'Singapura', country: 'Singapura', flag: 'singapura.png', isDaytime: true),
    WorldTime(url: 'Asia/Srednekolymsk', location: 'Srednekolymsk', country: 'Rússia', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Taipei', location: 'Taipei', country: 'China', flag: 'china.png', isDaytime: true),
    WorldTime(url: 'Asia/Tashkent', location: 'Tasquente', country: 'Uzbequistão', flag: 'uzbekistan.png', isDaytime: true),
    WorldTime(url: 'Asia/Tbilisi', location: 'Tiblíssi', country: 'Georgia', flag: 'georgia.png', isDaytime: true),
    WorldTime(url: 'Asia/Tehran', location: 'Teerã', country: 'Irã', flag: 'iran.png', isDaytime: true),
    WorldTime(url: 'Asia/Tel_Aviv', location: 'Tel Aviv', country: 'Israel', flag: 'israel.png', isDaytime: true),
    WorldTime(url: 'Asia/Thimbu', location: 'Thimbu', country: 'Butão', flag: 'bhutan.png', isDaytime: true),
    WorldTime(url: 'Asia/Thimphu', location: 'Thimphu', country: 'Butão', flag: 'bhutan.png', isDaytime: true),
    WorldTime(url: 'Asia/Tokyo', location: 'Tóquio', country: 'Japão', flag: 'japan.png', isDaytime: true),
    WorldTime(url: 'Asia/Tomsk', location: 'Tomsk', country: 'Rússia', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Ujung_Pandang', location: 'Ujung Pandang', country: 'Indonésia', flag: 'indonesia.png', isDaytime: true),
    WorldTime(url: 'Asia/Ulaanbaatar', location: 'Ulã Bator', country: 'Mongólia', flag: 'mongolia.png', isDaytime: true),
    WorldTime(url: 'Asia/Ulan_Bator', location: 'Ulan Bator', country: 'Mongólia', flag: 'mongolia.png', isDaytime: true),
    WorldTime(url: 'Asia/Urumqi', location: 'Ürümqi', country: 'China', flag: 'china.png', isDaytime: true),
    WorldTime(url: 'Asia/Ust-Nera', location: 'Ust-Nera', country: 'Rússia', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Vientiane', location: 'Vientiane', country: 'Laos', flag: 'laos.png', isDaytime: true),
    WorldTime(url: 'Asia/Vladivostok', location: 'Vladivostoque', country: 'Rússia', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Yakutsk', location: 'Iacutusque', country: 'Rússia', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Yangon', location: 'Rangum', country: 'Myanmar', flag: 'myanmar.png', isDaytime: true),
    WorldTime(url: 'Asia/Yekaterinburg', location: 'Ecaterimburgo', country: 'Rússia', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Asia/Yerevan', location: 'Erevã', country: 'Armênia', flag: 'armenia.png', isDaytime: true),
    WorldTime(url: 'Atlantic/Azores', location: 'Açores', country: 'Portugal', flag: 'portugal.png', isDaytime: true),
    WorldTime(url: 'Atlantic/Bermuda', location: 'Bermuda', country: 'Reino Unido', flag: 'reino_unido.png', isDaytime: true),
    WorldTime(url: 'Atlantic/Canary', location: 'Canary', country: 'Espanha', flag: 'espanha.png', isDaytime: true),
    WorldTime(url: 'Atlantic/Cape_Verde', location: 'Cabo Verde', country: 'Cabo Verde', flag: 'cabo_verde.png', isDaytime: true),
    WorldTime(url: 'Atlantic/Faeroe', location: 'Faroé', country: 'Dinamarca', flag: 'dinamarca.png', isDaytime: true),
    WorldTime(url: 'Atlantic/Faroe', location: 'Faroe', country: 'Dinamarca', flag: 'dinamarca.png', isDaytime: true),
    WorldTime(url: 'Atlantic/Jan_Mayen', location: 'Jan Mayen', country: 'Noruega', flag: 'noruega.png', isDaytime: true),
    WorldTime(url: 'Atlantic/Madeira', location: 'Madeira', country: 'Portugal', flag: 'portugal.png', isDaytime: true),
    WorldTime(url: 'Atlantic/Reykjavik', location: 'Reiquiavique', country: 'Islândia', flag: 'iceland.png', isDaytime: true),
    WorldTime(url: 'Atlantic/South_Georgia', location: 'Geórgia do Sul', country: 'Reino Unido', flag: 'reino_unido.png', isDaytime: true),
    WorldTime(url: 'Atlantic/St_Helena', location: 'Santa Helena', country: 'Reino Unido', flag: 'reino_unido.png', isDaytime: true),
    WorldTime(url: 'Atlantic/Stanley', location: 'Stanley', country: 'Reino Unido', flag: 'reino_unido.png', isDaytime: true),
    WorldTime(url: 'Australia/ACT', location: 'ACT', country: 'Austrália', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Adelaide', location: 'Adelaide', country: 'Austrália', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Brisbane', location: 'Brisbane', country: 'Austrália', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Broken_Hill', location: 'Broken Hill', country: 'Austrália', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Canberra', location: 'Camberra', country: 'Austrália', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Currie', location: 'Currie', country: 'Austrália', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Darwin', location: 'Darwin', country: 'Austrália', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Eucla', location: 'Eucla', country: 'Austrália', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Hobart', location: 'Hobart', country: 'Austrália', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/LHI', location: 'LHI', country: 'Austrália', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Lindeman', location: 'Lindeman', country: 'Austrália', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Lord_Howe', location: 'Lord Howe', country: 'Austrália', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Melbourne', location: 'Melbourne', country: 'Austrália', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/NSW', location: 'NSW', country: 'Austrália', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/North', location: 'North', country: 'Austrália', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Perth', location: 'Perth', country: 'Austrália', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Queensland', location: 'Queensland', country: 'Austrália', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/South', location: 'South', country: 'Austrália', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Sydney', location: 'Sydney', country: 'Austrália', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Tasmania', location: 'Tasmânia', country: 'Austrália', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Victoria', location: 'Victoria', country: 'Austrália', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/West', location: 'West', country: 'Austrália', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Australia/Yancowinna', location: 'Yancowinna', country: 'Austrália', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Brazil/Acre', location: 'Acre', country: 'Brasil', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'Brazil/DeNoronha', location: 'Fernando de Noronha', country: 'Brasil', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'Brazil/East', location: 'Leste', country: 'Brasil', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'Brazil/West', location: 'Oeste', country: 'Brasil', flag: 'brasil.png', isDaytime: true),
    WorldTime(url: 'CET', location: 'CET', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'CST6CDT', location: 'CST6CDT', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Canada/Atlantic', location: 'Atlantic', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'Canada/Central', location: 'Central', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'Canada/Eastern', location: 'Eastern', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'Canada/Mountain', location: 'Mountain', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'Canada/Newfoundland', location: 'Newfoundland and Labrador', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'Canada/Pacific', location: 'Pacific', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'Canada/Saskatchewan', location: 'Sascachevão', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'Canada/Yukon', location: 'Yukon', country: 'Canadá', flag: 'canada.png', isDaytime: true),
    WorldTime(url: 'Chile/Continental', location: 'Continental', country: 'Chile', flag: 'chile.png', isDaytime: true),
    WorldTime(url: 'Chile/EasterIsland', location: 'Ilha de Páscoa', country: 'Chile', flag: 'chile.png', isDaytime: true),
    WorldTime(url: 'Cuba', location: 'Cuba', country: 'Cuba', flag: 'cuba.png', isDaytime: true),
    WorldTime(url: 'EET', location: 'EET', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'EST', location: 'EST', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'EST5EDT', location: 'EST5EDT', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Egypt', location: 'Egito', country: 'Egito', flag: 'egito.png', isDaytime: true),
    WorldTime(url: 'Eire', location: 'Éire', country: 'Irlanda', flag: 'irlanda.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT', location: 'GMT', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT+0', location: 'GMT+0', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT+1', location: 'GMT+1', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT+10', location: 'GMT+10', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT+11', location: 'GMT+11', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT+12', location: 'GMT+12', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT+2', location: 'GMT+2', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT+3', location: 'GMT+3', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT+4', location: 'GMT+4', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT+5', location: 'GMT+5', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT+6', location: 'GMT+6', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT+7', location: 'GMT+7', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT+8', location: 'GMT+8', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT+9', location: 'GMT+9', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-0', location: 'GMT-0', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-1', location: 'GMT-1', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-10', location: 'GMT-10', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-11', location: 'GMT-11', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-12', location: 'GMT-12', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-13', location: 'GMT-13', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-14', location: 'GMT-14', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-2', location: 'GMT-2', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-3', location: 'GMT-3', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-4', location: 'GMT-4', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-5', location: 'GMT-5', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-6', location: 'GMT-6', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-7', location: 'GMT-7', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-8', location: 'GMT-8', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT-9', location: 'GMT-9', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/GMT0', location: 'GMT0', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/Greenwich', location: 'Greenwich', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/UCT', location: 'UCT', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/UTC', location: 'UTC', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/Universal', location: 'Universal', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Etc/Zulu', location: 'Zulu', country: 'África do Sul', flag: 'south_africa.png', isDaytime: true),
    WorldTime(url: 'Europe/Amsterdam', location: 'Amsterdã', country: 'Países Baixos', flag: 'nederland.png', isDaytime: true),
    WorldTime(url: 'Europe/Andorra', location: 'Andorra', country: 'Andorra', flag: 'andorra.png', isDaytime: true),
    WorldTime(url: 'Europe/Astrakhan', location: 'Astracã', country: 'Rússia', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Europe/Athens', location: 'Atenas', country: 'Grécia', flag: 'greece.png', isDaytime: true),
    WorldTime(url: 'Europe/Belfast', location: 'Belfaste', country: 'Reino Unido', flag: 'reino_unido.png', isDaytime: true),
    WorldTime(url: 'Europe/Belgrade', location: 'Belgrado', country: 'Sérvia', flag: 'serbia.png', isDaytime: true),
    WorldTime(url: 'Europe/Berlin', location: 'Berlim', country: 'Alemanha', flag: 'alemanha.png', isDaytime: true),
    WorldTime(url: 'Europe/Bratislava', location: 'Bratislava', country: 'Eslováquia', flag: 'slovakia.png', isDaytime: true),
    WorldTime(url: 'Europe/Brussels', location: 'Bruxelas', country: 'Bélgica', flag: 'belgium.png', isDaytime: true),
    WorldTime(url: 'Europe/Bucharest', location: 'Bucareste', country: 'Romênia', flag: 'romania.png', isDaytime: true),
    WorldTime(url: 'Europe/Budapest', location: 'Budapeste', country: 'Hungria', flag: 'hungria.png', isDaytime: true),
    WorldTime(url: 'Europe/Busingen', location: 'Büsingen no Alto Reno', country: 'Alemanha', flag: 'alemanha.png', isDaytime: true),
    WorldTime(url: 'Europe/Chisinau', location: 'Quixinau', country: 'Moldávia', flag: 'moldavia.png', isDaytime: true),
    WorldTime(url: 'Europe/Copenhagen', location: 'Copenhagen', country: 'Dinamarca', flag: 'dinamarca.png', isDaytime: true),
    WorldTime(url: 'Europe/Dublin', location: 'Dublin', country: 'Irlanda', flag: 'irlanda.png', isDaytime: true),
    WorldTime(url: 'Europe/Gibraltar', location: 'Gibraltar', country: 'Reino Unido', flag: 'reino_unido.png', isDaytime: true),
    WorldTime(url: 'Europe/Guernsey', location: 'Guernsey', country: 'Reino Unido', flag: 'reino_unido.png', isDaytime: true),
    WorldTime(url: 'Europe/Helsinki', location: 'Helsínquia', country: 'Finlândia', flag: 'finland.png', isDaytime: true),
    WorldTime(url: 'Europe/Isle_of_Man', location: 'Ilha dos Homens', country: 'Reino Unido', flag: 'reino_unido.png', isDaytime: true),
    WorldTime(url: 'Europe/Istanbul', location: 'Istambul', country: 'Turquia', flag: 'turquia.png', isDaytime: true),
    WorldTime(url: 'Europe/Jersey', location: 'Jersey', country: 'Reino Unido', flag: 'reino_unido.png', isDaytime: true),
    WorldTime(url: 'Europe/Kaliningrad', location: 'Kaliningrado', country: 'Rússia', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Europe/Kiev', location: 'Kiev', country: 'Ucrânia', flag: 'ukraine.png', isDaytime: true),
    WorldTime(url: 'Europe/Kirov', location: 'Kirov', country: 'Rússia', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Europe/Kyiv', location: 'Kyiv', country: 'Ucrânia', flag: 'ukraine.png', isDaytime: true),
    WorldTime(url: 'Europe/Lisbon', location: 'Lisboa', country: 'Portugal', flag: 'portugal.png', isDaytime: true),
    WorldTime(url: 'Europe/Ljubljana', location: 'Liubliana', country: 'Eslovênia', flag: 'slovenia.png', isDaytime: true),
    WorldTime(url: 'Europe/London', location: 'Londres', country: 'Reino Unido', flag: 'reino_unido.png', isDaytime: true),
    WorldTime(url: 'Europe/Luxembourg', location: 'Luxemburgo', country: 'Luxemburgo', flag: 'luxemburgo.png', isDaytime: true),
    WorldTime(url: 'Europe/Madrid', location: 'Madri', country: 'Espanha', flag: 'espanha.png', isDaytime: true),
    WorldTime(url: 'Europe/Malta', location: 'Malta', country: 'Malta', flag: 'malta.png', isDaytime: true),
    WorldTime(url: 'Europe/Mariehamn', location: 'Mariehamn', country: 'Finlândia', flag: 'finland.png', isDaytime: true),
    WorldTime(url: 'Europe/Minsk', location: 'Minsk', country: 'Bielorússia', flag: 'belarus.png', isDaytime: true),
    WorldTime(url: 'Europe/Monaco', location: 'Mônaco', country: 'Mônaco', flag: 'monaco.png', isDaytime: true),
    WorldTime(url: 'Europe/Moscow', location: 'Moscou', country: 'Rússia', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Europe/Nicosia', location: 'Nicosia', country: 'Chipre', flag: 'chipre.png', isDaytime: true),
    WorldTime(url: 'Europe/Oslo', location: 'Oslo', country: 'Noruega', flag: 'noruega.png', isDaytime: true),
    WorldTime(url: 'Europe/Paris', location: 'Paris', country: 'França', flag: 'france.png', isDaytime: true),
    WorldTime(url: 'Europe/Podgorica', location: 'Podgorica', country: 'Montenegro', flag: 'montenegro.png', isDaytime: true),
    WorldTime(url: 'Europe/Prague', location: 'Praga', country: 'República Tcheka', flag: 'czech_republic.png', isDaytime: true),
    WorldTime(url: 'Europe/Riga', location: 'Riga', country: 'Latvia', flag: 'latvia.png', isDaytime: true),
    WorldTime(url: 'Europe/Rome', location: 'Roma', country: 'Itália', flag: 'italy.png', isDaytime: true),
    WorldTime(url: 'Europe/Samara', location: 'Samara', country: 'Rússia', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Europe/San_Marino', location: 'San Marino', country: 'San Marino', flag: 'san_marino.png', isDaytime: true),
    WorldTime(url: 'Europe/Sarajevo', location: 'Sarajevo', country: 'Bósnia e Herzegovina', flag: 'bosnia_and_herzegovina.png', isDaytime: true),
    WorldTime(url: 'Europe/Saratov', location: 'Saratov', country: 'Rússia', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Europe/Simferopol', location: 'Simferopol', country: 'Ucrânia', flag: 'ukraine.png', isDaytime: true),
    WorldTime(url: 'Europe/Skopje', location: 'Escópia', country: 'Macedônia do Norte', flag: 'north_macedonia.png', isDaytime: true),
    WorldTime(url: 'Europe/Sofia', location: 'Sofia', country: 'Bulgária', flag: 'bulgaria.png', isDaytime: true),
    WorldTime(url: 'Europe/Stockholm', location: 'Estocolmo', country: 'Suécia', flag: 'sweden.png', isDaytime: true),
    WorldTime(url: 'Europe/Tallinn', location: 'Talim', country: 'Estônia', flag: 'estonia.png', isDaytime: true),
    WorldTime(url: 'Europe/Tirane', location: 'Tirana', country: 'Albânia', flag: 'albania.png', isDaytime: true),
    WorldTime(url: 'Europe/Tiraspol', location: 'Tiraspol', country: 'Moldávia', flag: 'moldavia.png', isDaytime: true),
    WorldTime(url: 'Europe/Ulyanovsk', location: 'Ulianovsk', country: 'Rússia', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Europe/Uzhgorod', location: 'Ujhorod', country: 'Ucrânia', flag: 'ukraine.png', isDaytime: true),
    WorldTime(url: 'Europe/Vaduz', location: 'Vaduz', country: 'Liechtenstein', flag: 'liechtenstein.png', isDaytime: true),
    WorldTime(url: 'Europe/Vatican', location: 'Vaticano', country: 'Vaticano', flag: 'vaticano.png', isDaytime: true),
    WorldTime(url: 'Europe/Vienna', location: 'Viena', country: 'Áustria', flag: 'austria.png', isDaytime: true),
    WorldTime(url: 'Europe/Vilnius', location: 'Vilnius', country: 'Lituânia', flag: 'lithuania.png', isDaytime: true),
    WorldTime(url: 'Europe/Volgograd', location: 'Volgogrado', country: 'Rússia', flag: 'russia.png', isDaytime: true),
    WorldTime(url: 'Europe/Warsaw', location: 'Varsóvia', country: 'Polônia', flag: 'poland.png', isDaytime: true),
    WorldTime(url: 'Europe/Zagreb', location: 'Zagreb', country: 'Croácia', flag: 'croatia.png', isDaytime: true),
    WorldTime(url: 'Europe/Zaporozhye', location: 'Zaporizhzhia', country: 'Ucrânia', flag: 'ukraine.png', isDaytime: true),
    WorldTime(url: 'Europe/Zurich', location: 'Zurique', country: 'Suíça', flag: 'swiss.png', isDaytime: true),
    WorldTime(url: 'GB', location: 'GB', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'GB-Eire', location: 'GB-Eire', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'GMT', location: 'GMT', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'GMT+0', location: 'GMT+0', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'GMT-0', location: 'GMT-0', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'GMT0', location: 'GMT0', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Greenwich', location: 'Greenwich', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'HST', location: 'HST', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Hongkong', location: 'Hong Kong', country: 'Hong Kong', flag: 'hong_kong.png', isDaytime: true),
    WorldTime(url: 'Iceland', location: 'Islândia', country: 'Islândia', flag: 'iceland.png', isDaytime: true),
    WorldTime(url: 'Indian/Antananarivo', location: 'Antananarivo', country: 'Madagascar', flag: 'madagascar.png', isDaytime: true),
    WorldTime(url: 'Indian/Chagos', location: 'Chagos', country: 'Maurício', flag: 'mauritius.png', isDaytime: true),
    WorldTime(url: 'Indian/Christmas', location: 'Christmas', country: 'Austrália', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Indian/Cocos', location: 'Cocos', country: 'Ausrália', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Indian/Comoro', location: 'Comoro', country: 'Indonésia', flag: 'indonesia.png', isDaytime: true),
    WorldTime(url: 'Indian/Kerguelen', location: 'Kerguelen', country: 'França', flag: 'france.png', isDaytime: true),
    WorldTime(url: 'Indian/Mahe', location: 'Mahé', country: 'Seicheles', flag: 'seychelles.png', isDaytime: true),
    WorldTime(url: 'Indian/Maldives', location: 'Maldivas', country: 'Maldivas', flag: 'maldivas.png', isDaytime: true),
    WorldTime(url: 'Indian/Mauritius', location: 'Maurícia', country: 'Maurício', flag: 'mauritius.png', isDaytime: true),
    WorldTime(url: 'Indian/Mayotte', location: 'Mayotte', country: 'França', flag: 'france.png', isDaytime: true),
    WorldTime(url: 'Indian/Reunion', location: 'Reunion', country: 'França', flag: 'france.png', isDaytime: true),
    WorldTime(url: 'Iran', location: 'Irã', country: 'Irã', flag: 'iran.png', isDaytime: true),
    WorldTime(url: 'Israel', location: 'Israel', country: 'Israel', flag: 'israel.png', isDaytime: true),
    WorldTime(url: 'Jamaica', location: 'Jamaica', country: 'Jamaica', flag: 'jamaica.png', isDaytime: true),
    WorldTime(url: 'Japan', location: 'Japão', country: 'Japão', flag: 'japan.png', isDaytime: true),
    WorldTime(url: 'Kwajalein', location: 'Kwajalein', country: 'Ilhas Marshall', flag: 'ilhas_marshall.png', isDaytime: true),
    WorldTime(url: 'Libya', location: 'Líbia', country: 'Líbia', flag: 'libya.png', isDaytime: true),
    WorldTime(url: 'MET', location: 'MET', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'MST', location: 'MST', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'MST7MDT', location: 'MST7MDT', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Mexico/BajaNorte', location: 'Baja Norte', country: 'México', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'Mexico/BajaSur', location: 'Baja Sur', country: 'México', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'Mexico/General', location: 'General', country: 'México', flag: 'mexico.png', isDaytime: true),
    WorldTime(url: 'NZ', location: 'NZ', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'NZ-CHA', location: 'NZ-CHA', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Navajo', location: 'Navajo', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'PRC', location: 'PRC', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'PST8PDT', location: 'PST8PDT', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Pacific/Apia', location: 'Apia', country: 'Samoa', flag: 'samoa.png', isDaytime: true),
    WorldTime(url: 'Pacific/Auckland', location: 'Auckland', country: 'Nova Zelândia', flag: 'new_zealand.png', isDaytime: true),
    WorldTime(url: 'Pacific/Bougainville', location: 'Bougainville', country: 'Papua Nova Guiné', flag: 'papua_new_guinea.png', isDaytime: true),
    WorldTime(url: 'Pacific/Chatham', location: 'Chatham', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'Pacific/Chuuk', location: 'Chuuk', country: 'Micronésia', flag: 'micronesia.png', isDaytime: true),
    WorldTime(url: 'Pacific/Easter', location: 'Páscoa', country: 'Chile', flag: 'chile.png', isDaytime: true),
    WorldTime(url: 'Pacific/Efate', location: 'Efate', country: 'Vanuatu', flag: 'vanuatu.png', isDaytime: true),
    WorldTime(url: 'Pacific/Enderbury', location: 'Enderbury', country: 'Reino Unido', flag: 'reino_unido.png', isDaytime: true),
    WorldTime(url: 'Pacific/Fakaofo', location: 'Fakaofo', country: 'Nova Zelândia', flag: 'new_zealand.png', isDaytime: true),
    WorldTime(url: 'Pacific/Fiji', location: 'Fiji', country: 'Fiji', flag: 'fiji.png', isDaytime: true),
    WorldTime(url: 'Pacific/Funafuti', location: 'Funafuti', country: 'Tuvalu', flag: 'tuvalu.png', isDaytime: true),
    WorldTime(url: 'Pacific/Galapagos', location: 'Galapagos', country: 'Equador', flag: 'equador.png', isDaytime: true),
    WorldTime(url: 'Pacific/Gambier', location: 'Gambier', country: 'França', flag: 'france.png', isDaytime: true),
    WorldTime(url: 'Pacific/Guadalcanal', location: 'Guadalcanal', country: 'Ilhas Salomão', flag: 'solomon_islands.png', isDaytime: true),
    WorldTime(url: 'Pacific/Guam', location: 'Guam', country: 'EUA', flag: 'guam.png', isDaytime: true),
    WorldTime(url: 'Pacific/Honolulu', location: 'Honolulu', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'Pacific/Johnston', location: 'Johnston', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'Pacific/Kanton', location: 'Kanton', country: 'Kiribati', flag: 'kiribati.png', isDaytime: true),
    WorldTime(url: 'Pacific/Kiritimati', location: 'Quiritimati', country: 'Kiribati', flag: 'kiribati.png', isDaytime: true),
    WorldTime(url: 'Pacific/Kosrae', location: 'Kosrae', country: 'Micronésia', flag: 'micronesia.png', isDaytime: true),
    WorldTime(url: 'Pacific/Kwajalein', location: 'Kwajalein', country: 'Ilhas Marshall', flag: 'ilhas_marshall.png', isDaytime: true),
    WorldTime(url: 'Pacific/Majuro', location: 'Majuro', country: 'Ilhas Marshall', flag: 'ilhas_marshall.png', isDaytime: true),
    WorldTime(url: 'Pacific/Marquesas', location: 'Marquesas', country: 'França', flag: 'france.png', isDaytime: true),
    WorldTime(url: 'Pacific/Midway', location: 'Midway', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'Pacific/Nauru', location: 'Nauru', country: 'Nauru', flag: 'nauru.png', isDaytime: true),
    WorldTime(url: 'Pacific/Niue', location: 'Niuê', country: 'Reino Unido', flag: 'niue.png', isDaytime: true),
    WorldTime(url: 'Pacific/Norfolk', location: 'Norfolque', country: 'Austrália', flag: 'australia.png', isDaytime: true),
    WorldTime(url: 'Pacific/Noumea', location: 'Numeá', country: 'França', flag: 'france.png', isDaytime: true),
    WorldTime(url: 'Pacific/Pago_Pago', location: 'Pago Pago', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'Pacific/Palau', location: 'Palau', country: 'Palau', flag: 'palau.png', isDaytime: true),
    WorldTime(url: 'Pacific/Pitcairn', location: 'Ilhas Pitcairn', country: 'Reino Unido', flag: 'ilhas_pitcairn.png', isDaytime: true),
    WorldTime(url: 'Pacific/Pohnpei', location: 'Pohnpei', country: 'Micronésia', flag: 'micronesia.png', isDaytime: true),
    WorldTime(url: 'Pacific/Ponape', location: 'Ponape', country: 'Micronésia', flag: 'micronesia.png', isDaytime: true),
    WorldTime(url: 'Pacific/Port_Moresby', location: 'Porto Moresby', country: 'Papua Nova Guiné', flag: 'papua_new_guinea.png', isDaytime: true),
    WorldTime(url: 'Pacific/Rarotonga', location: 'Rarotonga', country: 'Nova Zelândia', flag: 'new_zealand.png', isDaytime: true),
    WorldTime(url: 'Pacific/Saipan', location: 'Saipã', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'Pacific/Samoa', location: 'Samoa', country: 'Samoa', flag: 'samoa.png', isDaytime: true),
    WorldTime(url: 'Pacific/Tahiti', location: 'Tahiti', country: 'França', flag: 'france.png', isDaytime: true),
    WorldTime(url: 'Pacific/Tarawa', location: 'Taraua', country: 'Kiribati', flag: 'kiribati.png', isDaytime: true),
    WorldTime(url: 'Pacific/Tongatapu', location: 'Tongatapu', country: 'Tonga', flag: 'tonga.png', isDaytime: true),
    WorldTime(url: 'Pacific/Truk', location: 'Truk', country: 'Papua Nova Guiné', flag: 'papua_new_guinea.png', isDaytime: true),
    WorldTime(url: 'Pacific/Wake', location: 'Wake', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'Pacific/Wallis', location: 'Wallis', country: 'França', flag: 'france.png', isDaytime: true),
    WorldTime(url: 'Pacific/Yap', location: 'Yap', country: 'Micronésia', flag: 'micronesia.png', isDaytime: true),
    WorldTime(url: 'Poland', location: 'Polônia', country: 'Polônia', flag: 'poland.png', isDaytime: true),
    WorldTime(url: 'Portugal', location: 'Portugal', country: 'Portugal', flag: 'portugal.png', isDaytime: true),
    WorldTime(url: 'ROC', location: 'ROC', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'ROK', location: 'ROK', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Singapore', location: 'Singapura', country: 'Singapura', flag: 'singapura.png', isDaytime: true),
    WorldTime(url: 'Turkey', location: 'Turquia', country: 'Turquia', flag: 'turquia.png', isDaytime: true),
    WorldTime(url: 'UCT', location: 'UCT', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'US/Alaska', location: 'Alasca', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'US/Aleutian', location: 'Aleutian', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'US/Arizona', location: 'Arizona', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'US/Central', location: 'Central', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'US/East-Indiana', location: 'East-Indiana', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'US/Eastern', location: 'Eastern', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'US/Hawaii', location: 'Havaí', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'US/Indiana-Starke', location: 'Indiana-Starke', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'US/Michigan', location: 'Michigan', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'US/Mountain', location: 'Mountain', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'US/Pacific', location: 'Pacific', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'US/Samoa', location: 'Samoa', country: 'EUA', flag: 'eua.png', isDaytime: true),
    WorldTime(url: 'UTC', location: 'UTC', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Universal', location: 'Universal', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'W-SU', location: 'W-SU', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'WET', location: 'WET', flag: 'terra.png', isDaytime: true),
    WorldTime(url: 'Zulu', location: 'Zulu', country: 'África do Sul', flag: 'south_africa.png', isDaytime: true),
  ];

  @override
  void initState() {
    super.initState();
    locations.sort((a, b) {
      if (a.country == null && b.country == null) return 0;
      if (a.country == null) return 1;
      if (b.country == null) return -1;
      return a.country!.toLowerCase().compareTo(b.country!.toLowerCase());
    });
    filteredLocations = locations;
  }

  void _filterLocations(String query) {
    setState(() {
      filteredLocations = locations
          .where((location) =>
              location.location.toLowerCase().contains(query.toLowerCase()) ||
              (location.country?.toLowerCase().contains(query.toLowerCase()) ?? false))
          .toList();
    });
  }

  void updateTime(index) async {
    WorldTime instance = filteredLocations[index];
    await instance.getTime();
    // navigate to home screen
    Navigator.pop(context, {
      'location': instance.location,
      'flag': instance.flag,
      'time': instance.time,
      'isDaytime': instance.isDaytime,
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey[200],
      appBar: AppBar(
        backgroundColor: Colors.blue[900],
        title: isSearching
            ? TextField(
                controller: _searchController,
                autofocus: true,
                decoration: const InputDecoration(
                  hintText: 'Pesquisar...',
                  hintStyle: TextStyle(color: Colors.black),
                  border: InputBorder.none,
                ),
                style: const TextStyle(color: Colors.black),
                onChanged: _filterLocations,
              )
            : const Text('Escolha uma Localização'),
        centerTitle: true,
        elevation: 0,
        actions: [
          IconButton(
            icon: Icon(
              isSearching ? Icons.close : Icons.search,
              color: Colors.black,
            ),
            onPressed: () {
              setState(() {
                if (isSearching) {
                  isSearching = false;
                  _searchController.clear();
                  _filterLocations('');
                } else {
                  isSearching = true;
                }
              });
            },
          ),
        ],
      ),
      body: ListView.builder(
        itemCount: filteredLocations.length,
        itemBuilder: (context, index){
          return Padding(
            padding: const EdgeInsets.symmetric(vertical: 1.0, horizontal: 4.0),
            child: Card(
              child: ListTile(
                onTap: () {
                  updateTime(index);
                },
                title: Text(filteredLocations[index].location),
                subtitle: filteredLocations[index].country != null ? Text(
                  filteredLocations[index].country!,
                  style: TextStyle(
                    color: Colors.grey[600],
                  ),
                ) : null,
                leading: CircleAvatar(
                  backgroundImage: AssetImage('assets/${filteredLocations[index].flag}'),
                ),
              ),
            ),
          );
        }
      ),
    );
  }
}
